// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: abd.proto

#include "abd.pb.h"
#include "abd.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace abd {

static const char* ABDService_method_names[] = {
  "/abd.ABDService/WriteQuery",
  "/abd.ABDService/ReadQuery",
  "/abd.ABDService/WriteProp",
};

std::unique_ptr< ABDService::Stub> ABDService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ABDService::Stub> stub(new ABDService::Stub(channel, options));
  return stub;
}

ABDService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_WriteQuery_(ABDService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadQuery_(ABDService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteProp_(ABDService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ABDService::Stub::WriteQuery(::grpc::ClientContext* context, const ::abd::WriteQueryRequest& request, ::abd::WriteQueryReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::WriteQueryRequest, ::abd::WriteQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteQuery_, context, request, response);
}

void ABDService::Stub::async::WriteQuery(::grpc::ClientContext* context, const ::abd::WriteQueryRequest* request, ::abd::WriteQueryReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::WriteQueryRequest, ::abd::WriteQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteQuery_, context, request, response, std::move(f));
}

void ABDService::Stub::async::WriteQuery(::grpc::ClientContext* context, const ::abd::WriteQueryRequest* request, ::abd::WriteQueryReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::WriteQueryReply>* ABDService::Stub::PrepareAsyncWriteQueryRaw(::grpc::ClientContext* context, const ::abd::WriteQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::WriteQueryReply, ::abd::WriteQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::WriteQueryReply>* ABDService::Stub::AsyncWriteQueryRaw(::grpc::ClientContext* context, const ::abd::WriteQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ABDService::Stub::ReadQuery(::grpc::ClientContext* context, const ::abd::ReadQueryRequest& request, ::abd::ReadQueryReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::ReadQueryRequest, ::abd::ReadQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadQuery_, context, request, response);
}

void ABDService::Stub::async::ReadQuery(::grpc::ClientContext* context, const ::abd::ReadQueryRequest* request, ::abd::ReadQueryReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::ReadQueryRequest, ::abd::ReadQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadQuery_, context, request, response, std::move(f));
}

void ABDService::Stub::async::ReadQuery(::grpc::ClientContext* context, const ::abd::ReadQueryRequest* request, ::abd::ReadQueryReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::ReadQueryReply>* ABDService::Stub::PrepareAsyncReadQueryRaw(::grpc::ClientContext* context, const ::abd::ReadQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::ReadQueryReply, ::abd::ReadQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadQuery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::ReadQueryReply>* ABDService::Stub::AsyncReadQueryRaw(::grpc::ClientContext* context, const ::abd::ReadQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ABDService::Stub::WriteProp(::grpc::ClientContext* context, const ::abd::WritePropRequest& request, ::abd::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::WritePropRequest, ::abd::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteProp_, context, request, response);
}

void ABDService::Stub::async::WriteProp(::grpc::ClientContext* context, const ::abd::WritePropRequest* request, ::abd::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::WritePropRequest, ::abd::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteProp_, context, request, response, std::move(f));
}

void ABDService::Stub::async::WriteProp(::grpc::ClientContext* context, const ::abd::WritePropRequest* request, ::abd::Ack* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteProp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::Ack>* ABDService::Stub::PrepareAsyncWritePropRaw(::grpc::ClientContext* context, const ::abd::WritePropRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::Ack, ::abd::WritePropRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteProp_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::Ack>* ABDService::Stub::AsyncWritePropRaw(::grpc::ClientContext* context, const ::abd::WritePropRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWritePropRaw(context, request, cq);
  result->StartCall();
  return result;
}

ABDService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDService::Service, ::abd::WriteQueryRequest, ::abd::WriteQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::WriteQueryRequest* req,
             ::abd::WriteQueryReply* resp) {
               return service->WriteQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDService::Service, ::abd::ReadQueryRequest, ::abd::ReadQueryReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::ReadQueryRequest* req,
             ::abd::ReadQueryReply* resp) {
               return service->ReadQuery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDService::Service, ::abd::WritePropRequest, ::abd::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::WritePropRequest* req,
             ::abd::Ack* resp) {
               return service->WriteProp(ctx, req, resp);
             }, this)));
}

ABDService::Service::~Service() {
}

::grpc::Status ABDService::Service::WriteQuery(::grpc::ServerContext* context, const ::abd::WriteQueryRequest* request, ::abd::WriteQueryReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ABDService::Service::ReadQuery(::grpc::ServerContext* context, const ::abd::ReadQueryRequest* request, ::abd::ReadQueryReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ABDService::Service::WriteProp(::grpc::ServerContext* context, const ::abd::WritePropRequest* request, ::abd::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace abd
#include <grpcpp/ports_undef.inc>

