// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: abdv2.proto
// Protobuf C++ Version: 6.31.1

#include "abdv2.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace abdv2 {
template <typename>
PROTOBUF_CONSTEXPR WriteSetRet::WriteSetRet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(WriteSetRet_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct WriteSetRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteSetRetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteSetRetDefaultTypeInternal() {}
  union {
    WriteSetRet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteSetRetDefaultTypeInternal _WriteSetRet_default_instance_;

inline constexpr WriteSetArg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WriteSetArg::WriteSetArg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WriteSetArg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WriteSetArgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteSetArgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteSetArgDefaultTypeInternal() {}
  union {
    WriteSetArg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteSetArgDefaultTypeInternal _WriteSetArg_default_instance_;

inline constexpr WriteGetRet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}},
        client_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR WriteGetRet::WriteGetRet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WriteGetRet_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WriteGetRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteGetRetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteGetRetDefaultTypeInternal() {}
  union {
    WriteGetRet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteGetRetDefaultTypeInternal _WriteGetRet_default_instance_;

inline constexpr WriteGetArg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR WriteGetArg::WriteGetArg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WriteGetArg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WriteGetArgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteGetArgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteGetArgDefaultTypeInternal() {}
  union {
    WriteGetArg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteGetArgDefaultTypeInternal _WriteGetArg_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR ReadSetRet::ReadSetRet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(ReadSetRet_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct ReadSetRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadSetRetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadSetRetDefaultTypeInternal() {}
  union {
    ReadSetRet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadSetRetDefaultTypeInternal _ReadSetRet_default_instance_;

inline constexpr ReadSetArg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReadSetArg::ReadSetArg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReadSetArg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadSetArgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadSetArgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadSetArgDefaultTypeInternal() {}
  union {
    ReadSetArg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadSetArgDefaultTypeInternal _ReadSetArg_default_instance_;

inline constexpr ReadGetRet::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        val_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReadGetRet::ReadGetRet(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReadGetRet_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadGetRetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadGetRetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadGetRetDefaultTypeInternal() {}
  union {
    ReadGetRet _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadGetRetDefaultTypeInternal _ReadGetRet_default_instance_;

inline constexpr ReadGetArg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ReadGetArg::ReadGetArg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ReadGetArg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReadGetArgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadGetArgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadGetArgDefaultTypeInternal() {}
  union {
    ReadGetArg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadGetArgDefaultTypeInternal _ReadGetArg_default_instance_;
}  // namespace abdv2
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_abdv2_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_abdv2_2eproto = nullptr;
const ::uint32_t
    TableStruct_abdv2_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadGetArg, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadGetArg, _impl_.key_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadGetRet, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadGetRet, _impl_.val_),
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadGetRet, _impl_.timestamp_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadSetArg, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadSetArg, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadSetArg, _impl_.val_),
        PROTOBUF_FIELD_OFFSET(::abdv2::ReadSetArg, _impl_.timestamp_),
        0,
        1,
        2,
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetArg, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetArg, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetArg, _impl_.val_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetRet, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetRet, _impl_.val_),
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetRet, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteGetRet, _impl_.client_id_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteSetArg, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteSetArg, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteSetArg, _impl_.val_),
        PROTOBUF_FIELD_OFFSET(::abdv2::WriteSetArg, _impl_.timestamp_),
        0,
        1,
        2,
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::abdv2::ReadGetArg)},
        {5, sizeof(::abdv2::ReadGetRet)},
        {12, sizeof(::abdv2::ReadSetArg)},
        {21, sizeof(::abdv2::ReadSetRet)},
        {22, sizeof(::abdv2::WriteGetArg)},
        {29, sizeof(::abdv2::WriteGetRet)},
        {38, sizeof(::abdv2::WriteSetArg)},
        {47, sizeof(::abdv2::WriteSetRet)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::abdv2::_ReadGetArg_default_instance_._instance,
    &::abdv2::_ReadGetRet_default_instance_._instance,
    &::abdv2::_ReadSetArg_default_instance_._instance,
    &::abdv2::_ReadSetRet_default_instance_._instance,
    &::abdv2::_WriteGetArg_default_instance_._instance,
    &::abdv2::_WriteGetRet_default_instance_._instance,
    &::abdv2::_WriteSetArg_default_instance_._instance,
    &::abdv2::_WriteSetRet_default_instance_._instance,
};
const char descriptor_table_protodef_abdv2_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013abdv2.proto\022\005abdv2\"&\n\nReadGetArg\022\020\n\003ke"
    "y\030\001 \001(\tH\000\210\001\001B\006\n\004_key\"L\n\nReadGetRet\022\020\n\003va"
    "l\030\001 \001(\tH\000\210\001\001\022\026\n\ttimestamp\030\002 \001(\005H\001\210\001\001B\006\n\004"
    "_valB\014\n\n_timestamp\"f\n\nReadSetArg\022\020\n\003key\030"
    "\001 \001(\tH\000\210\001\001\022\020\n\003val\030\002 \001(\tH\001\210\001\001\022\026\n\ttimestam"
    "p\030\003 \001(\005H\002\210\001\001B\006\n\004_keyB\006\n\004_valB\014\n\n_timesta"
    "mp\"\014\n\nReadSetRet\"A\n\013WriteGetArg\022\020\n\003key\030\001"
    " \001(\tH\000\210\001\001\022\020\n\003val\030\002 \001(\tH\001\210\001\001B\006\n\004_keyB\006\n\004_"
    "val\"s\n\013WriteGetRet\022\020\n\003val\030\001 \001(\tH\000\210\001\001\022\026\n\t"
    "timestamp\030\002 \001(\003H\001\210\001\001\022\026\n\tclient_id\030\003 \001(\005H"
    "\002\210\001\001B\006\n\004_valB\014\n\n_timestampB\014\n\n_client_id"
    "\"g\n\013WriteSetArg\022\020\n\003key\030\001 \001(\tH\000\210\001\001\022\020\n\003val"
    "\030\002 \001(\tH\001\210\001\001\022\026\n\ttimestamp\030\003 \001(\005H\002\210\001\001B\006\n\004_"
    "keyB\006\n\004_valB\014\n\n_timestamp\"\r\n\013WriteSetRet"
    "2\333\001\n\007ABDImpl\0221\n\007ReadGet\022\021.abdv2.ReadGetA"
    "rg\032\021.abdv2.ReadGetRet\"\000\0221\n\007ReadSet\022\021.abd"
    "v2.ReadSetArg\032\021.abdv2.ReadSetRet\"\000\0224\n\010Wr"
    "iteGet\022\022.abdv2.WriteGetArg\032\022.abdv2.Write"
    "GetRet\"\000\0224\n\010WriteSet\022\022.abdv2.WriteSetArg"
    "\032\022.abdv2.WriteSetRet\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_abdv2_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_abdv2_2eproto = {
    false,
    false,
    790,
    descriptor_table_protodef_abdv2_2eproto,
    "abdv2.proto",
    &descriptor_table_abdv2_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_abdv2_2eproto::offsets,
    file_level_enum_descriptors_abdv2_2eproto,
    file_level_service_descriptors_abdv2_2eproto,
};
namespace abdv2 {
// ===================================================================

class ReadGetArg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReadGetArg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReadGetArg, _impl_._has_bits_);
};

ReadGetArg::ReadGetArg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadGetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.ReadGetArg)
}
PROTOBUF_NDEBUG_INLINE ReadGetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::ReadGetArg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_) {}

ReadGetArg::ReadGetArg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReadGetArg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadGetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadGetArg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:abdv2.ReadGetArg)
}
PROTOBUF_NDEBUG_INLINE ReadGetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena) {}

inline void ReadGetArg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ReadGetArg::~ReadGetArg() {
  // @@protoc_insertion_point(destructor:abdv2.ReadGetArg)
  SharedDtor(*this);
}
inline void ReadGetArg::SharedDtor(MessageLite& self) {
  ReadGetArg& this_ = static_cast<ReadGetArg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReadGetArg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadGetArg(arena);
}
constexpr auto ReadGetArg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReadGetArg),
                                            alignof(ReadGetArg));
}
constexpr auto ReadGetArg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadGetArg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadGetArg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReadGetArg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadGetArg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReadGetArg>(), &ReadGetArg::ByteSizeLong,
              &ReadGetArg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadGetArg, _impl_._cached_size_),
          false,
      },
      &ReadGetArg::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadGetArg_class_data_ =
        ReadGetArg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadGetArg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadGetArg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadGetArg_class_data_.tc_table);
  return ReadGetArg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2>
ReadGetArg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReadGetArg, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReadGetArg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::ReadGetArg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ReadGetArg, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string key = 1;
    {PROTOBUF_FIELD_OFFSET(ReadGetArg, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\3\0\0\0\0\0\0"
    "abdv2.ReadGetArg"
    "key"
  }},
};
PROTOBUF_NOINLINE void ReadGetArg::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.ReadGetArg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.key_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReadGetArg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReadGetArg& this_ = static_cast<const ReadGetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReadGetArg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReadGetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.ReadGetArg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string key = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.ReadGetArg.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.ReadGetArg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReadGetArg::ByteSizeLong(const MessageLite& base) {
  const ReadGetArg& this_ = static_cast<const ReadGetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReadGetArg::ByteSizeLong() const {
  const ReadGetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.ReadGetArg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional string key = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_key());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReadGetArg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadGetArg*>(&to_msg);
  auto& from = static_cast<const ReadGetArg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.ReadGetArg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadGetArg::CopyFrom(const ReadGetArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.ReadGetArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadGetArg::InternalSwap(ReadGetArg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
}

::google::protobuf::Metadata ReadGetArg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReadGetRet::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReadGetRet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_._has_bits_);
};

ReadGetRet::ReadGetRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadGetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.ReadGetRet)
}
PROTOBUF_NDEBUG_INLINE ReadGetRet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::ReadGetRet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        val_(arena, from.val_) {}

ReadGetRet::ReadGetRet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReadGetRet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadGetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadGetRet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:abdv2.ReadGetRet)
}
PROTOBUF_NDEBUG_INLINE ReadGetRet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        val_(arena) {}

inline void ReadGetRet::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
ReadGetRet::~ReadGetRet() {
  // @@protoc_insertion_point(destructor:abdv2.ReadGetRet)
  SharedDtor(*this);
}
inline void ReadGetRet::SharedDtor(MessageLite& self) {
  ReadGetRet& this_ = static_cast<ReadGetRet&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.val_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReadGetRet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadGetRet(arena);
}
constexpr auto ReadGetRet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReadGetRet),
                                            alignof(ReadGetRet));
}
constexpr auto ReadGetRet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadGetRet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadGetRet::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReadGetRet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadGetRet::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReadGetRet>(), &ReadGetRet::ByteSizeLong,
              &ReadGetRet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_._cached_size_),
          false,
      },
      &ReadGetRet::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadGetRet_class_data_ =
        ReadGetRet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadGetRet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadGetRet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadGetRet_class_data_.tc_table);
  return ReadGetRet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2>
ReadGetRet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReadGetRet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::ReadGetRet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReadGetRet, _impl_.timestamp_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_.timestamp_)}},
    // optional string val = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_.val_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string val = 1;
    {PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_.val_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(ReadGetRet, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\20\3\0\0\0\0\0\0"
    "abdv2.ReadGetRet"
    "val"
  }},
};
PROTOBUF_NOINLINE void ReadGetRet::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.ReadGetRet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.val_.ClearNonDefaultToEmpty();
  }
  _impl_.timestamp_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReadGetRet::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReadGetRet& this_ = static_cast<const ReadGetRet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReadGetRet::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReadGetRet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.ReadGetRet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string val = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_val();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.ReadGetRet.val");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int32 timestamp = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_timestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.ReadGetRet)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReadGetRet::ByteSizeLong(const MessageLite& base) {
  const ReadGetRet& this_ = static_cast<const ReadGetRet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReadGetRet::ByteSizeLong() const {
  const ReadGetRet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.ReadGetRet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional string val = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_val());
    }
    // optional int32 timestamp = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_timestamp());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReadGetRet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadGetRet*>(&to_msg);
  auto& from = static_cast<const ReadGetRet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.ReadGetRet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_val(from._internal_val());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadGetRet::CopyFrom(const ReadGetRet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.ReadGetRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadGetRet::InternalSwap(ReadGetRet* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.val_, &other->_impl_.val_, arena);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata ReadGetRet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReadSetArg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ReadSetArg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_._has_bits_);
};

ReadSetArg::ReadSetArg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadSetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.ReadSetArg)
}
PROTOBUF_NDEBUG_INLINE ReadSetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::ReadSetArg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        val_(arena, from.val_) {}

ReadSetArg::ReadSetArg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReadSetArg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ReadSetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadSetArg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:abdv2.ReadSetArg)
}
PROTOBUF_NDEBUG_INLINE ReadSetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        val_(arena) {}

inline void ReadSetArg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
ReadSetArg::~ReadSetArg() {
  // @@protoc_insertion_point(destructor:abdv2.ReadSetArg)
  SharedDtor(*this);
}
inline void ReadSetArg::SharedDtor(MessageLite& self) {
  ReadSetArg& this_ = static_cast<ReadSetArg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.val_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ReadSetArg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadSetArg(arena);
}
constexpr auto ReadSetArg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReadSetArg),
                                            alignof(ReadSetArg));
}
constexpr auto ReadSetArg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadSetArg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadSetArg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ReadSetArg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadSetArg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ReadSetArg>(), &ReadSetArg::ByteSizeLong,
              &ReadSetArg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_._cached_size_),
          false,
      },
      &ReadSetArg::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadSetArg_class_data_ =
        ReadSetArg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadSetArg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadSetArg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadSetArg_class_data_.tc_table);
  return ReadSetArg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 31, 2>
ReadSetArg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReadSetArg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::ReadSetArg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.key_)}},
    // optional string val = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.val_)}},
    // optional int32 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReadSetArg, _impl_.timestamp_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string key = 1;
    {PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string val = 2;
    {PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.val_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(ReadSetArg, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\20\3\3\0\0\0\0\0"
    "abdv2.ReadSetArg"
    "key"
    "val"
  }},
};
PROTOBUF_NOINLINE void ReadSetArg::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.ReadSetArg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.val_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.timestamp_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ReadSetArg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ReadSetArg& this_ = static_cast<const ReadSetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ReadSetArg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ReadSetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.ReadSetArg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string key = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.ReadSetArg.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string val = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_val();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.ReadSetArg.val");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 timestamp = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_timestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.ReadSetArg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ReadSetArg::ByteSizeLong(const MessageLite& base) {
  const ReadSetArg& this_ = static_cast<const ReadSetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ReadSetArg::ByteSizeLong() const {
  const ReadSetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.ReadSetArg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // optional string key = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_key());
    }
    // optional string val = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_val());
    }
    // optional int32 timestamp = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_timestamp());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ReadSetArg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReadSetArg*>(&to_msg);
  auto& from = static_cast<const ReadSetArg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.ReadSetArg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_key(from._internal_key());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_val(from._internal_val());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReadSetArg::CopyFrom(const ReadSetArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.ReadSetArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReadSetArg::InternalSwap(ReadSetArg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.val_, &other->_impl_.val_, arena);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata ReadSetArg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReadSetRet::_Internal {
 public:
};

ReadSetRet::ReadSetRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, ReadSetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:abdv2.ReadSetRet)
}
ReadSetRet::ReadSetRet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ReadSetRet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, ReadSetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReadSetRet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:abdv2.ReadSetRet)
}

inline void* PROTOBUF_NONNULL ReadSetRet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ReadSetRet(arena);
}
constexpr auto ReadSetRet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReadSetRet),
                                            alignof(ReadSetRet));
}
constexpr auto ReadSetRet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ReadSetRet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ReadSetRet::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<ReadSetRet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ReadSetRet::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<ReadSetRet>(), &ReadSetRet::ByteSizeLong,
              &ReadSetRet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ReadSetRet, _impl_._cached_size_),
          false,
      },
      &ReadSetRet::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ReadSetRet_class_data_ =
        ReadSetRet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ReadSetRet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ReadSetRet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ReadSetRet_class_data_.tc_table);
  return ReadSetRet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
ReadSetRet::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ReadSetRet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::ReadSetRet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata ReadSetRet::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WriteGetArg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WriteGetArg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_._has_bits_);
};

WriteGetArg::WriteGetArg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteGetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.WriteGetArg)
}
PROTOBUF_NDEBUG_INLINE WriteGetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::WriteGetArg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        val_(arena, from.val_) {}

WriteGetArg::WriteGetArg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WriteGetArg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteGetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WriteGetArg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:abdv2.WriteGetArg)
}
PROTOBUF_NDEBUG_INLINE WriteGetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        val_(arena) {}

inline void WriteGetArg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
WriteGetArg::~WriteGetArg() {
  // @@protoc_insertion_point(destructor:abdv2.WriteGetArg)
  SharedDtor(*this);
}
inline void WriteGetArg::SharedDtor(MessageLite& self) {
  WriteGetArg& this_ = static_cast<WriteGetArg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.val_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WriteGetArg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WriteGetArg(arena);
}
constexpr auto WriteGetArg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WriteGetArg),
                                            alignof(WriteGetArg));
}
constexpr auto WriteGetArg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WriteGetArg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WriteGetArg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WriteGetArg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WriteGetArg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WriteGetArg>(), &WriteGetArg::ByteSizeLong,
              &WriteGetArg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_._cached_size_),
          false,
      },
      &WriteGetArg::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WriteGetArg_class_data_ =
        WriteGetArg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WriteGetArg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WriteGetArg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WriteGetArg_class_data_.tc_table);
  return WriteGetArg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
WriteGetArg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WriteGetArg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::WriteGetArg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string val = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_.val_)}},
    // optional string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string key = 1;
    {PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string val = 2;
    {PROTOBUF_FIELD_OFFSET(WriteGetArg, _impl_.val_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\3\3\0\0\0\0\0"
    "abdv2.WriteGetArg"
    "key"
    "val"
  }},
};
PROTOBUF_NOINLINE void WriteGetArg::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.WriteGetArg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.val_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WriteGetArg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WriteGetArg& this_ = static_cast<const WriteGetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WriteGetArg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WriteGetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.WriteGetArg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string key = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.WriteGetArg.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string val = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_val();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.WriteGetArg.val");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.WriteGetArg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WriteGetArg::ByteSizeLong(const MessageLite& base) {
  const WriteGetArg& this_ = static_cast<const WriteGetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WriteGetArg::ByteSizeLong() const {
  const WriteGetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.WriteGetArg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional string key = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_key());
    }
    // optional string val = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_val());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WriteGetArg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WriteGetArg*>(&to_msg);
  auto& from = static_cast<const WriteGetArg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.WriteGetArg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_key(from._internal_key());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_val(from._internal_val());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WriteGetArg::CopyFrom(const WriteGetArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.WriteGetArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WriteGetArg::InternalSwap(WriteGetArg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.val_, &other->_impl_.val_, arena);
}

::google::protobuf::Metadata WriteGetArg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WriteGetRet::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WriteGetRet>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_._has_bits_);
};

WriteGetRet::WriteGetRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteGetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.WriteGetRet)
}
PROTOBUF_NDEBUG_INLINE WriteGetRet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::WriteGetRet& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        val_(arena, from.val_) {}

WriteGetRet::WriteGetRet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WriteGetRet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteGetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WriteGetRet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, client_id_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::client_id_));

  // @@protoc_insertion_point(copy_constructor:abdv2.WriteGetRet)
}
PROTOBUF_NDEBUG_INLINE WriteGetRet::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        val_(arena) {}

inline void WriteGetRet::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, client_id_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::client_id_));
}
WriteGetRet::~WriteGetRet() {
  // @@protoc_insertion_point(destructor:abdv2.WriteGetRet)
  SharedDtor(*this);
}
inline void WriteGetRet::SharedDtor(MessageLite& self) {
  WriteGetRet& this_ = static_cast<WriteGetRet&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.val_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WriteGetRet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WriteGetRet(arena);
}
constexpr auto WriteGetRet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WriteGetRet),
                                            alignof(WriteGetRet));
}
constexpr auto WriteGetRet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WriteGetRet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WriteGetRet::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WriteGetRet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WriteGetRet::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WriteGetRet>(), &WriteGetRet::ByteSizeLong,
              &WriteGetRet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_._cached_size_),
          false,
      },
      &WriteGetRet::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WriteGetRet_class_data_ =
        WriteGetRet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WriteGetRet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WriteGetRet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WriteGetRet_class_data_.tc_table);
  return WriteGetRet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 29, 2>
WriteGetRet::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WriteGetRet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::WriteGetRet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string val = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.val_)}},
    // optional int64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WriteGetRet, _impl_.timestamp_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.timestamp_)}},
    // optional int32 client_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WriteGetRet, _impl_.client_id_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.client_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string val = 1;
    {PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.val_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 client_id = 3;
    {PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.client_id_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\3\0\0\0\0\0\0"
    "abdv2.WriteGetRet"
    "val"
  }},
};
PROTOBUF_NOINLINE void WriteGetRet::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.WriteGetRet)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.val_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.client_id_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.client_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WriteGetRet::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WriteGetRet& this_ = static_cast<const WriteGetRet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WriteGetRet::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WriteGetRet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.WriteGetRet)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string val = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_val();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.WriteGetRet.val");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int64 timestamp = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
            stream, this_._internal_timestamp(), target);
  }

  // optional int32 client_id = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_client_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.WriteGetRet)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WriteGetRet::ByteSizeLong(const MessageLite& base) {
  const WriteGetRet& this_ = static_cast<const WriteGetRet&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WriteGetRet::ByteSizeLong() const {
  const WriteGetRet& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.WriteGetRet)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // optional string val = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_val());
    }
    // optional int64 timestamp = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_timestamp());
    }
    // optional int32 client_id = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_client_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WriteGetRet::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WriteGetRet*>(&to_msg);
  auto& from = static_cast<const WriteGetRet&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.WriteGetRet)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_val(from._internal_val());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.client_id_ = from._impl_.client_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WriteGetRet::CopyFrom(const WriteGetRet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.WriteGetRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WriteGetRet::InternalSwap(WriteGetRet* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.val_, &other->_impl_.val_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.client_id_)
      + sizeof(WriteGetRet::_impl_.client_id_)
      - PROTOBUF_FIELD_OFFSET(WriteGetRet, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata WriteGetRet::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WriteSetArg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WriteSetArg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_._has_bits_);
};

WriteSetArg::WriteSetArg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteSetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:abdv2.WriteSetArg)
}
PROTOBUF_NDEBUG_INLINE WriteSetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::abdv2::WriteSetArg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        val_(arena, from.val_) {}

WriteSetArg::WriteSetArg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WriteSetArg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WriteSetArg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WriteSetArg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:abdv2.WriteSetArg)
}
PROTOBUF_NDEBUG_INLINE WriteSetArg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        val_(arena) {}

inline void WriteSetArg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
WriteSetArg::~WriteSetArg() {
  // @@protoc_insertion_point(destructor:abdv2.WriteSetArg)
  SharedDtor(*this);
}
inline void WriteSetArg::SharedDtor(MessageLite& self) {
  WriteSetArg& this_ = static_cast<WriteSetArg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.val_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WriteSetArg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WriteSetArg(arena);
}
constexpr auto WriteSetArg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(WriteSetArg),
                                            alignof(WriteSetArg));
}
constexpr auto WriteSetArg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WriteSetArg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WriteSetArg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WriteSetArg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WriteSetArg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WriteSetArg>(), &WriteSetArg::ByteSizeLong,
              &WriteSetArg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_._cached_size_),
          false,
      },
      &WriteSetArg::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WriteSetArg_class_data_ =
        WriteSetArg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WriteSetArg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WriteSetArg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WriteSetArg_class_data_.tc_table);
  return WriteSetArg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 32, 2>
WriteSetArg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WriteSetArg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::WriteSetArg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.key_)}},
    // optional string val = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.val_)}},
    // optional int32 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(WriteSetArg, _impl_.timestamp_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string key = 1;
    {PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string val = 2;
    {PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.val_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(WriteSetArg, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\3\3\0\0\0\0\0"
    "abdv2.WriteSetArg"
    "key"
    "val"
  }},
};
PROTOBUF_NOINLINE void WriteSetArg::Clear() {
// @@protoc_insertion_point(message_clear_start:abdv2.WriteSetArg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.val_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.timestamp_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WriteSetArg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WriteSetArg& this_ = static_cast<const WriteSetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WriteSetArg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WriteSetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:abdv2.WriteSetArg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string key = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.WriteSetArg.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string val = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_val();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "abdv2.WriteSetArg.val");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 timestamp = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_timestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:abdv2.WriteSetArg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WriteSetArg::ByteSizeLong(const MessageLite& base) {
  const WriteSetArg& this_ = static_cast<const WriteSetArg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WriteSetArg::ByteSizeLong() const {
  const WriteSetArg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:abdv2.WriteSetArg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // optional string key = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_key());
    }
    // optional string val = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_val());
    }
    // optional int32 timestamp = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_timestamp());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WriteSetArg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<WriteSetArg*>(&to_msg);
  auto& from = static_cast<const WriteSetArg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:abdv2.WriteSetArg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_key(from._internal_key());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_val(from._internal_val());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void WriteSetArg::CopyFrom(const WriteSetArg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:abdv2.WriteSetArg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WriteSetArg::InternalSwap(WriteSetArg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.val_, &other->_impl_.val_, arena);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata WriteSetArg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WriteSetRet::_Internal {
 public:
};

WriteSetRet::WriteSetRet(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, WriteSetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:abdv2.WriteSetRet)
}
WriteSetRet::WriteSetRet(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WriteSetRet& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, WriteSetRet_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WriteSetRet* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:abdv2.WriteSetRet)
}

inline void* PROTOBUF_NONNULL WriteSetRet::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WriteSetRet(arena);
}
constexpr auto WriteSetRet::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WriteSetRet),
                                            alignof(WriteSetRet));
}
constexpr auto WriteSetRet::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WriteSetRet_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WriteSetRet::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<WriteSetRet>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WriteSetRet::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<WriteSetRet>(), &WriteSetRet::ByteSizeLong,
              &WriteSetRet::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WriteSetRet, _impl_._cached_size_),
          false,
      },
      &WriteSetRet::kDescriptorMethods,
      &descriptor_table_abdv2_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WriteSetRet_class_data_ =
        WriteSetRet::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WriteSetRet::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WriteSetRet_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WriteSetRet_class_data_.tc_table);
  return WriteSetRet_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
WriteSetRet::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WriteSetRet_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::abdv2::WriteSetRet>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata WriteSetRet::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace abdv2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_abdv2_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
