// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: abdv2.proto
#ifndef GRPC_abdv2_2eproto__INCLUDED
#define GRPC_abdv2_2eproto__INCLUDED

#include "abdv2.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace abdv2 {

// ABD Algorithm service definition.
class ABDImpl final {
 public:
  static constexpr char const* service_full_name() {
    return "abdv2.ABDImpl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Responds to a read phase 1 request.
    virtual ::grpc::Status ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::abdv2::ReadGetRet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>> AsyncReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>>(AsyncReadGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>> PrepareAsyncReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>>(PrepareAsyncReadGetRaw(context, request, cq));
    }
    // Responds to a read phase 2 request.
    virtual ::grpc::Status ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::abdv2::ReadSetRet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>> AsyncReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>>(AsyncReadSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>> PrepareAsyncReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>>(PrepareAsyncReadSetRaw(context, request, cq));
    }
    // Responds to a write phase 1 request.
    virtual ::grpc::Status WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::abdv2::WriteGetRet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>> AsyncWriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>>(AsyncWriteGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>> PrepareAsyncWriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>>(PrepareAsyncWriteGetRaw(context, request, cq));
    }
    // Responds to a write phase 2 request.
    virtual ::grpc::Status WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::abdv2::WriteSetRet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>> AsyncWriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>>(AsyncWriteSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>> PrepareAsyncWriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>>(PrepareAsyncWriteSetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Responds to a read phase 1 request.
      virtual void ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Responds to a read phase 2 request.
      virtual void ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Responds to a write phase 1 request.
      virtual void WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Responds to a write phase 2 request.
      virtual void WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, std::function<void(::grpc::Status)>) = 0;
      virtual void WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>* AsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadGetRet>* PrepareAsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>* AsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::ReadSetRet>* PrepareAsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>* AsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteGetRet>* PrepareAsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>* AsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::abdv2::WriteSetRet>* PrepareAsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::abdv2::ReadGetRet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>> AsyncReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>>(AsyncReadGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>> PrepareAsyncReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>>(PrepareAsyncReadGetRaw(context, request, cq));
    }
    ::grpc::Status ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::abdv2::ReadSetRet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>> AsyncReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>>(AsyncReadSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>> PrepareAsyncReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>>(PrepareAsyncReadSetRaw(context, request, cq));
    }
    ::grpc::Status WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::abdv2::WriteGetRet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>> AsyncWriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>>(AsyncWriteGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>> PrepareAsyncWriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>>(PrepareAsyncWriteGetRaw(context, request, cq));
    }
    ::grpc::Status WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::abdv2::WriteSetRet* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>> AsyncWriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>>(AsyncWriteSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>> PrepareAsyncWriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>>(PrepareAsyncWriteSetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, std::function<void(::grpc::Status)>) override;
      void ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, std::function<void(::grpc::Status)>) override;
      void ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, std::function<void(::grpc::Status)>) override;
      void WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, ::grpc::ClientUnaryReactor* reactor) override;
      void WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, std::function<void(::grpc::Status)>) override;
      void WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>* AsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>* PrepareAsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>* AsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>* PrepareAsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>* AsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>* PrepareAsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>* AsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>* PrepareAsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReadGet_;
    const ::grpc::internal::RpcMethod rpcmethod_ReadSet_;
    const ::grpc::internal::RpcMethod rpcmethod_WriteGet_;
    const ::grpc::internal::RpcMethod rpcmethod_WriteSet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Responds to a read phase 1 request.
    virtual ::grpc::Status ReadGet(::grpc::ServerContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response);
    // Responds to a read phase 2 request.
    virtual ::grpc::Status ReadSet(::grpc::ServerContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response);
    // Responds to a write phase 1 request.
    virtual ::grpc::Status WriteGet(::grpc::ServerContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response);
    // Responds to a write phase 2 request.
    virtual ::grpc::Status WriteSet(::grpc::ServerContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadGet() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadGet(::grpc::ServerContext* context, ::abdv2::ReadGetArg* request, ::grpc::ServerAsyncResponseWriter< ::abdv2::ReadGetRet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReadSet() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadSet(::grpc::ServerContext* context, ::abdv2::ReadSetArg* request, ::grpc::ServerAsyncResponseWriter< ::abdv2::ReadSetRet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WriteGet() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteGet(::grpc::ServerContext* context, ::abdv2::WriteGetArg* request, ::grpc::ServerAsyncResponseWriter< ::abdv2::WriteGetRet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_WriteSet() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteSet(::grpc::ServerContext* context, ::abdv2::WriteSetArg* request, ::grpc::ServerAsyncResponseWriter< ::abdv2::WriteSetRet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReadGet<WithAsyncMethod_ReadSet<WithAsyncMethod_WriteGet<WithAsyncMethod_WriteSet<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadGet() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::abdv2::ReadGetArg, ::abdv2::ReadGetRet>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response) { return this->ReadGet(context, request, response); }));}
    void SetMessageAllocatorFor_ReadGet(
        ::grpc::MessageAllocator< ::abdv2::ReadGetArg, ::abdv2::ReadGetRet>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::abdv2::ReadGetArg, ::abdv2::ReadGetRet>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadGet(
      ::grpc::CallbackServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReadSet() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::abdv2::ReadSetArg, ::abdv2::ReadSetRet>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response) { return this->ReadSet(context, request, response); }));}
    void SetMessageAllocatorFor_ReadSet(
        ::grpc::MessageAllocator< ::abdv2::ReadSetArg, ::abdv2::ReadSetRet>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::abdv2::ReadSetArg, ::abdv2::ReadSetRet>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadSet(
      ::grpc::CallbackServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WriteGet() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::abdv2::WriteGetArg, ::abdv2::WriteGetRet>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response) { return this->WriteGet(context, request, response); }));}
    void SetMessageAllocatorFor_WriteGet(
        ::grpc::MessageAllocator< ::abdv2::WriteGetArg, ::abdv2::WriteGetRet>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::abdv2::WriteGetArg, ::abdv2::WriteGetRet>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteGet(
      ::grpc::CallbackServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_WriteSet() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::abdv2::WriteSetArg, ::abdv2::WriteSetRet>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response) { return this->WriteSet(context, request, response); }));}
    void SetMessageAllocatorFor_WriteSet(
        ::grpc::MessageAllocator< ::abdv2::WriteSetArg, ::abdv2::WriteSetRet>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::abdv2::WriteSetArg, ::abdv2::WriteSetRet>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteSet(
      ::grpc::CallbackServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReadGet<WithCallbackMethod_ReadSet<WithCallbackMethod_WriteGet<WithCallbackMethod_WriteSet<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadGet() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReadSet() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WriteGet() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_WriteSet() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadGet() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReadSet() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReadSet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WriteGet() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_WriteSet() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWriteSet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadGet() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadGet(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadGet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReadSet() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReadSet(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReadSet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WriteGet() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WriteGet(context, request, response); }));
    }
    ~WithRawCallbackMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteGet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_WriteSet() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->WriteSet(context, request, response); }));
    }
    ~WithRawCallbackMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* WriteSet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadGet() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::abdv2::ReadGetArg, ::abdv2::ReadGetRet>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::abdv2::ReadGetArg, ::abdv2::ReadGetRet>* streamer) {
                       return this->StreamedReadGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadGet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadGetArg* /*request*/, ::abdv2::ReadGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::abdv2::ReadGetArg,::abdv2::ReadGetRet>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReadSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReadSet() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::abdv2::ReadSetArg, ::abdv2::ReadSetRet>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::abdv2::ReadSetArg, ::abdv2::ReadSetRet>* streamer) {
                       return this->StreamedReadSet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReadSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReadSet(::grpc::ServerContext* /*context*/, const ::abdv2::ReadSetArg* /*request*/, ::abdv2::ReadSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReadSet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::abdv2::ReadSetArg,::abdv2::ReadSetRet>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WriteGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WriteGet() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::abdv2::WriteGetArg, ::abdv2::WriteGetRet>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::abdv2::WriteGetArg, ::abdv2::WriteGetRet>* streamer) {
                       return this->StreamedWriteGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WriteGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WriteGet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteGetArg* /*request*/, ::abdv2::WriteGetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWriteGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::abdv2::WriteGetArg,::abdv2::WriteGetRet>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_WriteSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_WriteSet() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::abdv2::WriteSetArg, ::abdv2::WriteSetRet>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::abdv2::WriteSetArg, ::abdv2::WriteSetRet>* streamer) {
                       return this->StreamedWriteSet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_WriteSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status WriteSet(::grpc::ServerContext* /*context*/, const ::abdv2::WriteSetArg* /*request*/, ::abdv2::WriteSetRet* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWriteSet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::abdv2::WriteSetArg,::abdv2::WriteSetRet>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReadGet<WithStreamedUnaryMethod_ReadSet<WithStreamedUnaryMethod_WriteGet<WithStreamedUnaryMethod_WriteSet<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReadGet<WithStreamedUnaryMethod_ReadSet<WithStreamedUnaryMethod_WriteGet<WithStreamedUnaryMethod_WriteSet<Service > > > > StreamedService;
};

}  // namespace abdv2


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_abdv2_2eproto__INCLUDED
