// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: abdv2.proto

#include "abdv2.pb.h"
#include "abdv2.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace abdv2 {

static const char* ABDImpl_method_names[] = {
  "/abdv2.ABDImpl/ReadGet",
  "/abdv2.ABDImpl/ReadSet",
  "/abdv2.ABDImpl/WriteGet",
  "/abdv2.ABDImpl/WriteSet",
};

std::unique_ptr< ABDImpl::Stub> ABDImpl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ABDImpl::Stub> stub(new ABDImpl::Stub(channel, options));
  return stub;
}

ABDImpl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReadGet_(ABDImpl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadSet_(ABDImpl_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteGet_(ABDImpl_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteSet_(ABDImpl_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ABDImpl::Stub::ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::abdv2::ReadGetRet* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abdv2::ReadGetArg, ::abdv2::ReadGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadGet_, context, request, response);
}

void ABDImpl::Stub::async::ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abdv2::ReadGetArg, ::abdv2::ReadGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadGet_, context, request, response, std::move(f));
}

void ABDImpl::Stub::async::ReadGet(::grpc::ClientContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>* ABDImpl::Stub::PrepareAsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abdv2::ReadGetRet, ::abdv2::ReadGetArg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadGet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abdv2::ReadGetRet>* ABDImpl::Stub::AsyncReadGetRaw(::grpc::ClientContext* context, const ::abdv2::ReadGetArg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ABDImpl::Stub::ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::abdv2::ReadSetRet* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abdv2::ReadSetArg, ::abdv2::ReadSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadSet_, context, request, response);
}

void ABDImpl::Stub::async::ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abdv2::ReadSetArg, ::abdv2::ReadSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadSet_, context, request, response, std::move(f));
}

void ABDImpl::Stub::async::ReadSet(::grpc::ClientContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>* ABDImpl::Stub::PrepareAsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abdv2::ReadSetRet, ::abdv2::ReadSetArg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abdv2::ReadSetRet>* ABDImpl::Stub::AsyncReadSetRaw(::grpc::ClientContext* context, const ::abdv2::ReadSetArg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ABDImpl::Stub::WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::abdv2::WriteGetRet* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abdv2::WriteGetArg, ::abdv2::WriteGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteGet_, context, request, response);
}

void ABDImpl::Stub::async::WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abdv2::WriteGetArg, ::abdv2::WriteGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteGet_, context, request, response, std::move(f));
}

void ABDImpl::Stub::async::WriteGet(::grpc::ClientContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>* ABDImpl::Stub::PrepareAsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abdv2::WriteGetRet, ::abdv2::WriteGetArg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteGet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abdv2::WriteGetRet>* ABDImpl::Stub::AsyncWriteGetRaw(::grpc::ClientContext* context, const ::abdv2::WriteGetArg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ABDImpl::Stub::WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::abdv2::WriteSetRet* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abdv2::WriteSetArg, ::abdv2::WriteSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteSet_, context, request, response);
}

void ABDImpl::Stub::async::WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abdv2::WriteSetArg, ::abdv2::WriteSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteSet_, context, request, response, std::move(f));
}

void ABDImpl::Stub::async::WriteSet(::grpc::ClientContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>* ABDImpl::Stub::PrepareAsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abdv2::WriteSetRet, ::abdv2::WriteSetArg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abdv2::WriteSetRet>* ABDImpl::Stub::AsyncWriteSetRaw(::grpc::ClientContext* context, const ::abdv2::WriteSetArg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

ABDImpl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDImpl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDImpl::Service, ::abdv2::ReadGetArg, ::abdv2::ReadGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDImpl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abdv2::ReadGetArg* req,
             ::abdv2::ReadGetRet* resp) {
               return service->ReadGet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDImpl_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDImpl::Service, ::abdv2::ReadSetArg, ::abdv2::ReadSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDImpl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abdv2::ReadSetArg* req,
             ::abdv2::ReadSetRet* resp) {
               return service->ReadSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDImpl_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDImpl::Service, ::abdv2::WriteGetArg, ::abdv2::WriteGetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDImpl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abdv2::WriteGetArg* req,
             ::abdv2::WriteGetRet* resp) {
               return service->WriteGet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ABDImpl_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ABDImpl::Service, ::abdv2::WriteSetArg, ::abdv2::WriteSetRet, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ABDImpl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abdv2::WriteSetArg* req,
             ::abdv2::WriteSetRet* resp) {
               return service->WriteSet(ctx, req, resp);
             }, this)));
}

ABDImpl::Service::~Service() {
}

::grpc::Status ABDImpl::Service::ReadGet(::grpc::ServerContext* context, const ::abdv2::ReadGetArg* request, ::abdv2::ReadGetRet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ABDImpl::Service::ReadSet(::grpc::ServerContext* context, const ::abdv2::ReadSetArg* request, ::abdv2::ReadSetRet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ABDImpl::Service::WriteGet(::grpc::ServerContext* context, const ::abdv2::WriteGetArg* request, ::abdv2::WriteGetRet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ABDImpl::Service::WriteSet(::grpc::ServerContext* context, const ::abdv2::WriteSetArg* request, ::abdv2::WriteSetRet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace abdv2
#include <grpcpp/ports_undef.inc>

